# How to communicate your results

In this chapter, we are going to discuss, presenting your results to people at various levels of an organization. This will include people ranging from management, and other analysts, to people in the C-Suite. There are some elements that are common when you are presenting your results, and then there are other elements which are going to be more specific, depending on what a person's responsibilities include.

I've had the opportunity to manage multi-million dollar accounts for a fortune 1000 company, I've also run two volunteer nonprofits, a chapter of Amnesty International, and the Chicago Apple User Group.My work also includes several nonprofit social service organizations. I've also run my own vacation rental business, and I've done a lot of volunteer work. Therefore, I can speak from a wide range of experience on business needs.

## A very basic introduction to financial reporting

### Always give the best service you can possibly do: The Ritz Carlton method

## Help your manager make the best possible decisions

## Have empathy for your manager's—and customer's— situations

### don't need them in any way

### Have a great story to tell—How to create a great story

### Br prepared with strong counterexamples

### include uncertainty

### tell the (hard) truth, prepare them for criticism

## Communicating results with staff who have Profit and Loss responsibility

### Vision, mission, values - what is the central question?

### Financials

### The higher up the org chart, the more you will be working with vision, stragety, financials

## Communicating with customers and vendors

## Communicating ROI and other results of data science

## Social media and more
